# Generated by Django 5.2.7 on 2025-10-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="message",
            name="unique_message_sequence_per_conversation",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="chat_messag_convers_300ced_idx",
            old_name="chat_msg_conv_seq_idx",
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("conversation", "sequence")},
        ),
        migrations.AddField(
            model_name="feedback",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="chat.message",
            ),
        ),
    ]
